### ISSUE TITLE
После обновления на 0.114 ошибка при загрузке

### ISSUE THREAD

**Issue by kevinblo** [AlexxIT/PythonScriptsPro#1]
```
2020-08-14 08:27:02 ERROR (SyncWorker_6) [custom_components.python_script] Error executing script: length of value must be at least 1 for dictionary value @ data['options']
Traceback (most recent call last):
  File "/config/custom_components/python_script/__init__.py", line 81, in execute_script    exec(code)
  File "<string>", line 5, in <module>  File "/usr/src/homeassistant/homeassistant/core.py", line 1220, in call    return asyncio.run_coroutine_threadsafe(
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 439, in result    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result    raise self._exception
  File "/usr/src/homeassistant/homeassistant/core.py", line 1262, in async_call    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 208, in __call__    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 287, in _exec    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 283, in _exec    v = func(v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable    return schema(data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: length of value must be at least 1 for dictionary value @ data['options']
```

**Comment by AlexxIT** [comment]
Поправлено на последних версиях? А то я не уследил за ошибкой

**Comment by AlexxIT** [comment]
Probably not relevant
