### ISSUE TITLE
Character set 'utf8' unsupported after update to HA 2022.7.7 in script 

### ISSUE THREAD

**Issue by mcpfr** [AlexxIT/PythonScriptsPro#11]
Hello,

I have this error after update my HA (downgrade have not change), advance that my script worked perfectly

Can you help me
```
Cette erreur provient d'une intégration personnalisée

Logger: custom_components.python_script
Source: config_mcp/scripts_python/actif/suppression_state_attributes_base.py:5
Integration: Python Scripts Pro (documentation, issues)
First occurred: 03:15:32 (1 occurrences)
Last logged: 03:15:32

Error executing script: Character set 'utf8' unsupported
Traceback (most recent call last):
  File "/config/custom_components/python_script/__init__.py", line 81, in execute_script
    exec(code)
  File "/config/config_mcp/scripts_python/actif/suppression_state_attributes_base.py", line 5, in <module>
    connexion = mysql.connector.connect(host="core-mariadb", user="xxxxxx", password="xxxxx", database="homeassistant", charset="utf8")
  File "/usr/local/lib/python3.10/site-packages/mysql/connector/pooling.py", line 287, in connect
    return MySQLConnection(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mysql/connector/connection.py", line 137, in __init__
    self.connect(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/mysql/connector/abstracts.py", line 1092, in connect
    self.config(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/mysql/connector/abstracts.py", line 516, in config
    self._charset_id = CharacterSet.get_charset_info(charset, collation)[0]
  File "/usr/local/lib/python3.10/site-packages/mysql/connector/constants.py", line 775, in get_charset_info
    info = cls.get_default_collation(charset)
  File "/usr/local/lib/python3.10/site-packages/mysql/connector/constants.py", line 746, in get_default_collation
    raise ProgrammingError(f"Character set '{charset}' unsupported")
mysql.connector.errors.ProgrammingError: Character set 'utf8' unsupported
```

**Comment by AlexxIT** [comment]
Not related to this integration. It' your DB or mysql library problem.
