### ISSUE TITLE
error accessing component files from the script

### ISSUE THREAD

**Issue by malinovsku** [AlexxIT/PythonScriptsPro#23]
in release 1.0.0, the behavior of running scripts has changed. Previously, there was a file next to the component for receiving data to access secrets, but now an error occurs at startup
secrets.py
```
def get_secret(key):
    s = {}
    with open('/config/secrets.yaml', encoding='utf-8-sig') as f:
        for line in f.readlines():
            p = line.split(":")
            if len(p) > 1:
                s[p[0].strip()] = ":".join(p[1:]).strip()
    return s[key]
```

in the executable file as an example
```
from .secrets import get_secret
token = get_secret('telegram_bot_token')
```

Error
```
ERROR (SyncWorker_12) [custom_components.python_script] Error executing script
Traceback (most recent call last):
  File "/config/custom_components/python_script/__init__.py", line 118, in execute_script
    exec(code, locals())
  File "/config/python_scripts/new2.py", line 2, in <module>
    from .secrets import get_secret
KeyError: "'__name__' not in globals"
```

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/PythonScriptsPro/releases/tag/v1.0.1
