### ISSUE TITLE
Не устанавливаются библиотеки

### ISSUE THREAD

**Issue by profx5015** [AlexxIT/PythonScriptsPro#32]
Добрый день!
В configuration.yaml прописаны требуемые библиотеки.
При попытке запуска скрипта возникает ошибка error: No module named 'matplotlib'
Раньше работало, но после обновления - перестало.
Текущая версия HA 2024.7.3

python_script:
  requirements:
  - paramiko>=2.7.1
  - matplotlib>=3.9.0
  - requests>=2.0.0
  - beautifulsoup4>=4.0.0
  - Pillow>=10.0.0
  - qrcode>=7.0.0
  - numpy>=1.26.0
  - Cython>=3.0.0
  - dateparser>=1.1.0

`Error executing script
Traceback (most recent call last):
  File "/config/custom_components/python_script/__init__.py", line 106, in execute_script
    exec(code, vars)
  File "/config/scripts/plot.py", line 5, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'`

<details><summary>Скриншот</summary>
<p>

![Alt text](https://github.com/user-attachments/assets/af8999f7-ee1f-4849-a7d1-a10102ca5ed5 "Screenshot")

</p>
</details>

**Comment by AlexxIT** [comment]
Two options. Either you didn't wait for the installation. Or this dependency cannot be installed in the HA environment (this also happens).
