### ISSUE TITLE
No Module Named Error

### ISSUE THREAD

**Issue by marcolinux46** [AlexxIT/PythonScriptsPro#34]
Hi @AlexxIT 

Following there is a log from home assistant when i run a script from developer tools.

Traceback (most recent call last):
  File "/config/custom_components/python_script/__init__.py", line 106, in execute_script
    exec(code, vars)
  File "/config/custom_components/wireproxy/check_connectedvpn_geolite.py", line 1, in <module>
    from geoip2 import database, errors
ModuleNotFoundError: No module named 'geoip2'

The module is installed and the script runs perfectly on command line via SSH

Can you help me?

**Comment by AlexxIT** [comment]
Show how you script looks like.

**Comment by marcolinux46** [comment]
Hi @AlexxIT 

here the script

import geoip2.database
import geoip2.errors
import os

command = "curl --proxy http://xxx.xxx.xxx.xxx:8080 https://wtfismyip.com/text"
result = (os.popen(command).read()).strip()

with geoip2.database.Reader('GeoLite2-City.mmdb') as reader:
    try:
        response = reader.city(result)
        ip = response.traits.ip_address
#        timezone = response.location.time_zone.split("/",1)
        city = response.city.name
        country = response.country.names["en"]
        if country == "Poland" and (city == "Warsaw" or timezone == "Warsaw"):
            result = "Poland Warsaw"
        elif country == "Poland" and (city == "Gdansk" or timezone == "Gdansk"):
            result = "Poland Gdansk"
        else:
            result = "Errore..."

        hass.states.set('input_text.wireproxy_activevpn', country, {'friendly_name':'Nazione VPN','icon':'mdi:vpn'})
        hass.states.set('input_text.wireproxy_ip', ip, {'friendly_name':'VPN IP','icon':'mdi:ip'})
        print(city)
        print(ip)
        print(country)
    except geoip2.errors.AddressNotFoundError as e:
        response = None
        noip = "IP Not Found in DB..."
        print("IP Not Found in DB...")
        hass.states.set('input_text.wireproxy_activevpn', noip, {'friendly_name':'Nazione VPN','icon':'mdi:vpn'})

**Comment by AlexxIT** [comment]
But your error refers to a completely different code.

**Comment by marcolinux46** [comment]
Yes infact the error don't sync with the code.
this string "from geoip2 import database, errors" was the first release of the script but after 10 minutes i modified the code

**Comment by AlexxIT** [comment]
Are you sure your code not in cache? You needs to restart Hass after any changes or disable cache.

**Comment by marcolinux46** [comment]
Ok... How can i disable cache?
Now i try to restart hass and i will let you know

**Comment by marcolinux46** [comment]
I just restarted Hass, but only the service not the entire OS, but nothing happen
I have HAOS not docker or supervised

**Comment by kini24** [comment]
Такая же проблема в HA Supervised. В configuration.yaml прописал
```
python_script:
  requirements:
    - beautifulsoup4>=4.0.0
    - lxml>=5.0.0
```
Создал новый файл скрипта, добавил строки
```
import requests
import json
import beautifulsoup4
```
При запуске получаю
```
Traceback (most recent call last):
  File "/config/python_scripts/kes.py", line 3, in <module>
    import beautifulsoup4
ModuleNotFoundError: No module named 'beautifulsoup4'
```
Пробовал написать и bs4, и bs, и beautifulsoup - результат тот же. В логах ХА пусто, отладку не включал (как?) Установлены последние версии

**Comment by marcolinux46** [comment]
Hi @kini24,

i resolved the issue entering in the docker instance and installing the missing module.
You have to connect through SSH with protection mode disabled and executing the following commands:

sudo docker exec -it homeassistant /bin/bash
pip3 install bs4 --break-system-packages

Now you can try to exec the script in HA and everything should be fine

**Comment by kini24** [comment]
Unfortunately, I also tried your option. I'm sorry I didn't mention this earlier. I rebooted HA, entered the commands again, got
```
# pip3 install bs4 --break-system-packages
Looking in indexes: https://pypi.org/simple, https://wheels.home-assistant.io/musllinux-index/
Requirement already satisfied: bs4 in /usr/local/lib/python3.13/site-packages (0.0.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.13/site-packages (from bs4) (4.12.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/site-packages (from beautifulsoup4->bs4) (2.6)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
```
